apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: sbs-frontend-config
  namespace: sbs-namespace
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
