apiVersion: v1
kind: Service
metadata:
  # FIX: Respect the fullnameOverride if provided
  name: {{ .Values.frontend.fullnameOverride | default (printf "%s-frontend" .Release.Name) }}
  labels:
    app: sbs-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: sbs-frontend