services:
  sbs-service:
    build: .
    image: sbs-solver:latest
    container_name: sbs_service
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      # - SBS_DICT=/app/data/custom_dict.txt
    volumes:
      - ./data:/app/data
    restart: unless-stopped
