replicaCount: 2
backend:
  image:
    repository: gcr.io/sbs-solver/sbs-backend
    tag: latest
frontend:
  image:
    repository: gcr.io/sbs-solver/sbs-frontend
    tag: latest
  service:
    type: NodePort
ingress:
  enabled: true
  host: sbsolver.ch
  staticIpName: sbs-global-ip