apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.fullnameOverride | default (printf "%s-backend" .Release.Name) }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.fullnameOverride | default (printf "%s-backend" .Release.Name) }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.fullnameOverride | default (printf "%s-backend" .Release.Name) }}
    spec:
      volumes:
        - name: data-volume
          emptyDir: {}
      initContainers:
        - name: download-dictionary
          image: curlimages/curl:latest
          args: ["-L", "-o", "/app/data/dictionary.txt", "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt"]
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SBS_DICT
              value: "/app/data/dictionary.txt"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data