apiVersion: v1
kind: Service
metadata:
  # This line now honors the --set frontend.fullnameOverride from your Makefile
  name: {{ .Values.frontend.fullnameOverride | default (printf "%s-frontend" .Release.Name) }}
  annotations:
    {{- if .Values.ingress.enabled }}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end }}
spec:
  type: {{ .Values.frontend.service.type | default "NodePort" }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.frontend.fullnameOverride | default (printf "%s-frontend" .Release.Name) }}