apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.fullnameOverride | default "sbs-frontend" }}
  labels:
    app: sbs-frontend
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: sbs-frontend