apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.fullnameOverride | default (printf "%s-frontend" .Release.Name) }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.fullnameOverride | default (printf "%s-frontend" .Release.Name) }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.fullnameOverride | default (printf "%s-frontend" .Release.Name) }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - name: http
              containerPort: 80