{{- if .Values.certificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.certificate.name }}
spec:
  domains:
    - {{ .Values.ingress.host }}
{{- end }}
